### PR TITLE
Update graphicHelper.js

### PR DESCRIPTION
**Pull request by danielmalencar**
Extend the hover area of marks issue#99

Currently, in order to select a marking like a ray-line, one needs to know exactly where the marked points are and hover over it. The hover area should be extended to the entire line(s) and a few pixels near the line to make selecting it easier. Bonus, the cursor should be changed to pointer when hover over a marking for good UX as well.

### CODE REVIEW

**Comment by fuzzthink** [comment]
@danielmalencar For me, the change didn't do anything as it never got to that point for rayLine for me. It always returns in the conditional above that. See https://github.com/liihuu/KLineChart/issues/99 .

**Comment by danielmalencar** [comment]
Works fine with another graphic marks

**Comment by fuzzthink** [comment]
Verified this PR works along with the missing "key" param in https://github.com/liihuu/KLineChart/pull/101 .

**Comment by liihuu** [comment]
@fuzzthink is right. 😄

**Pull request closed without merging**
