### PR TITLE
update addData to accept both directions

### PR DESCRIPTION
**Pull request by oneart-dev**
Fix for issue described here https://github.com/liihuu/KLineChart/issues/442

### CODE REVIEW

**Review by liihuu — COMMENTED** [review]
Is `updateData` ?

**Comment by oneart-dev** [comment]
> Is `updateData` ?

updateData does not accept KLineData[] ony KLineData. It's not an efficient way to pass for example 1k klines but we are using updateData for now

**Comment by liihuu** [comment]
The first time loading data, the latest should be loaded, and 'updateData' is used for real-time updates.

**Comment by oneart-dev** [comment]
Its not possible for us. For example, we are showing the trade happened at 2020 on 1M timeframe. We can't load everything, only small part of data between trade entry and exit.

**Pull request closed without merging**
